"""Internet Archive clients and models."""

import logging

from archivist.services.internet_archive.async_client import AsyncInternetArchiveClient
from archivist.services.internet_archive.client import InternetArchiveClient
from archivist.services.internet_archive.item_models import (
    InternetArchiveAddFilesError,
    InternetArchiveAddFilesFileResult,
    InternetArchiveAddFilesResult,
    InternetArchiveChecksumState,
    InternetArchiveFileDisposition,
    InternetArchiveItem,
    InternetArchiveItemAvailability,
    InternetArchiveItemFile,
    InternetArchiveItemFileSource,
    InternetArchiveItemTask,
    InternetArchiveItemTaskState,
    InternetArchiveRecoveryDeferredError,
    InternetArchiveRecoveryError,
    InternetArchiveRecoveryFileResult,
    InternetArchiveRecoveryPhase,
    InternetArchiveRecoveryResult,
    InternetArchiveRemovalResult,
    InternetArchiveUploadError,
    InternetArchiveUploadFile,
    InternetArchiveUploadFileResult,
    InternetArchiveUploadOptions,
    InternetArchiveUploadResult,
)
from archivist.services.internet_archive.models import (
    InternetArchiveAccount,
    InternetArchiveApiKey,
    InternetArchiveAvailability,
    InternetArchiveCaptureJob,
    InternetArchiveCaptureStatus,
    InternetArchiveCdxRecord,
    InternetArchiveCdxResult,
    InternetArchiveCookies,
    InternetArchiveFailedStatus,
    InternetArchiveOutlinkAvailability,
    InternetArchivePendingStatus,
    InternetArchiveSaveOptions,
    InternetArchiveSnapshot,
    InternetArchiveSuccessStatus,
    InternetArchiveSystemStatus,
    InternetArchiveUserStatus,
)

logger = logging.getLogger(__name__)

__all__ = [
    "AsyncInternetArchiveClient",
    "InternetArchiveAccount",
    "InternetArchiveAddFilesError",
    "InternetArchiveAddFilesFileResult",
    "InternetArchiveAddFilesResult",
    "InternetArchiveApiKey",
    "InternetArchiveAvailability",
    "InternetArchiveCaptureJob",
    "InternetArchiveCaptureStatus",
    "InternetArchiveCdxRecord",
    "InternetArchiveCdxResult",
    "InternetArchiveChecksumState",
    "InternetArchiveClient",
    "InternetArchiveCookies",
    "InternetArchiveFailedStatus",
    "InternetArchiveFileDisposition",
    "InternetArchiveItem",
    "InternetArchiveItemAvailability",
    "InternetArchiveItemFile",
    "InternetArchiveItemFileSource",
    "InternetArchiveItemTask",
    "InternetArchiveItemTaskState",
    "InternetArchiveOutlinkAvailability",
    "InternetArchivePendingStatus",
    "InternetArchiveRecoveryDeferredError",
    "InternetArchiveRecoveryError",
    "InternetArchiveRecoveryFileResult",
    "InternetArchiveRecoveryPhase",
    "InternetArchiveRecoveryResult",
    "InternetArchiveRemovalResult",
    "InternetArchiveSaveOptions",
    "InternetArchiveSnapshot",
    "InternetArchiveSuccessStatus",
    "InternetArchiveSystemStatus",
    "InternetArchiveUploadError",
    "InternetArchiveUploadFile",
    "InternetArchiveUploadFileResult",
    "InternetArchiveUploadOptions",
    "InternetArchiveUploadResult",
    "InternetArchiveUserStatus",
]
